require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rake
  - rubocop-performance

AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

RSpec/EmptyExampleGroup:
  Exclude:
    - "**/*swagger_spec.rb"

RSpec/NestedGroups:
  Max: 4
  
RSpec/ExampleLength:
  Enabled: false

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table
