x-app: &app
  build:
    context: .
    dockerfile: dev.dockerfile
  image: lateral-link/haistack-coding-challenge
  platform: linux/amd64
  volumes:
    - .:/app
    - app_gem_home:/usr/local/bundle

services:

  app:
    <<: *app
    depends_on:
      - db
      - webpacker
    environment:
      DATABASE_URL: $DATABASE_URL
      NODE_ENV: development
      RAILS_ENV: development
      WEBPACKER_DEV_SERVER_HOST: webpacker
    ports:
      - "3000:3000"

  webpacker:
    <<: *app
    command: bundle exec ./bin/webpack-dev-server
    environment:
      NODE_ENV: development
      RAILS_ENV: development
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
    ports:
      - "3035:3035"

  db:
    environment:
      MYSQL_DATABASE: $DB_DATABASE
      MYSQL_ONETIME_PASSWORD: true
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_RANDOM_ROOT_PASSWORD: true
      MYSQL_USER: $DB_USERNAME
    image: mysql:5.7.41-debian
    platform: linux/amd64
    ports:
      - "3306:3306"
    volumes:
      - db_mysql_datadir:/var/lib/mysql

volumes:

  app_gem_home:
  db_mysql_datadir:
